# NO-OP placeholder that always passes for other paths
# This is here so that we're able to set the status check as required

name: Verify Accessibility Core features Placeholder
on:
  pull_request:
    branches: [master]
    paths-ignore:
      - 'plugins/catalog/**'
      - 'plugins/techdocs/**'
      - 'plugins/scaffolder/**'
      - 'plugins/search/**'

jobs:
  noop:
    name: Accessibility
    runs-on: ubuntu-latest
    steps:
      - run: echo NOOP
